export const getProductFields = (t) => [
    { label: t("spreadsheetIgnoreField", { defaultValue: "Ignore this field" }), value: "" },
    { label: t("spreadsheetProductId", { defaultValue: "Product ID" }), value: "id" },
    { label: t("spreadsheetVariantId", { defaultValue: "Variant ID" }), value: "variant_id" },
    { label: t("title", { defaultValue: "Title" }), value: "title" },
    { label: t("description", { defaultValue: "Description" }), value: "description" },
    { label: t("vendor", { defaultValue: "Vendor" }), value: "vendor" },
    { label: t("productType", { defaultValue: "Product Type" }), value: "productType" },
    { label: t("handle", { defaultValue: "Handle" }), value: "handle" },
    { label: t("status", { defaultValue: "Status" }), value: "status" },
    { label: t("tags", { defaultValue: "Tags" }), value: "tags" },
    { label: t("spreadsheetSeoMetaTitle", { defaultValue: "SEO Meta Title" }), value: "metaTitle" },
    { label: t("spreadsheetSeoMetaDescription", { defaultValue: "SEO Meta Description" }), value: "metaDescription" },
    { label: t("price", { defaultValue: "Price" }), value: "price" },
    { label: t("spreadsheetCompareAtPrice", { defaultValue: "Compare At Price" }), value: "compareAtPrice" },
    { label: t("sku", { defaultValue: "SKU" }), value: "sku" },
    { label: t("barcode", { defaultValue: "Barcode" }), value: "barcode" },
    { label: t("spreadsheetTaxable", { defaultValue: "Taxable" }), value: "taxable" },
];
