# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "20f31d269398d5f23df95d0450e772e9"
name = "test-app"

application_url = "https://reduction-initiative-loving-august.trycloudflare.com"
>>>>>>> 0b0179c0a1b7ca7093f836ee98f3a7a3082dafe8
embedded = true
handle = "test-app-11537"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [
  "products/delete",
  "inventory_levels/connect",
  "inventory_items/create",
  "inventory_levels/disconnect",
  "inventory_levels/update",
  "collections/delete",
  "app/uninstalled",
  "bulk_operations/finish",
  "collections/update",
  "products/create",
  "collections/create",
  "shop/update",
  "inventory_items/update",
  "inventory_items/delete",
  "products/update"
]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_metaobjects,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
<<<<<<< HEAD
  "https://tea-ralph-brooklyn-trout.trycloudflare.com/auth/callback",
  "https://tea-ralph-brooklyn-trout.trycloudflare.com/auth/shopify/callback",
  "https://tea-ralph-brooklyn-trout.trycloudflare.com/api/auth/callback"
=======
  "https://reduction-initiative-loving-august.trycloudflare.com/auth/callback",
  "https://reduction-initiative-loving-august.trycloudflare.com/auth/shopify/callback",
  "https://reduction-initiative-loving-august.trycloudflare.com/api/auth/callback"
>>>>>>> 0b0179c0a1b7ca7093f836ee98f3a7a3082dafe8
]

[app_proxy]
url = "https://automatic-learners-excluded-decorative.trycloudflare.com/storefront/subscription"
subpath = "proxy"
prefix = "apps"
