export const STRING_OPERATORS = [
  "equals",
  "is",
  "is not",
  "does not equal",
  "contains",
  "does not contain",
  "starts with",
  "ends with",
  "in",
  "is empty",
  "is empty/blank",
  "is not empty",
];

export const ENUM_OPERATORS = [
  "equals",
  "is",
  "is not",
  "does not equal",
  "in",
  "is empty",
  "is empty/blank",
  "is not empty",
];

export const NUMBER_OPERATORS = [
  "<",
  "<=",
  ">",
  ">=",
  "=",
  "!=",
  "equals",
  "is",
  "is not",
  "does not equal",
  "less than",
  "less than or equal",
  "greater than",
  "greater than or equal",
  "in",
  "is empty",
  "is empty/blank",
  "is not empty",
];

export const DATE_OPERATORS = [
  "is before",
  "is after",
  "is on",
  "is before x days ago",
  "is after x days ago",
  "in",
  "is empty",
  "is empty/blank",
  "is not empty",
];

export const OPERATOR_COST = {
  "=": 0.05,
  equals: 0.05,
  is: 0.05,
  "is not": 0.85,
  "does not equal": 0.85,
  "!=": 0.85,
  contains: 0.45,
  "does not contain": 0.95,
  "starts with": 0.25,
  "ends with": 0.65,
  "<": 0.35,
  "<=": 0.4,
  ">": 0.35,
  ">=": 0.4,
  "less than": 0.35,
  "less than or equal": 0.4,
  "greater than": 0.35,
  "greater than or equal": 0.4,
  "is empty": 0.2,
  "is empty/blank": 0.2,
  "is not empty": 0.8,
  "is before": 0.35,
  "is after": 0.35,
  "is on": 0.08,
  "is before x days ago": 0.35,
  "is after x days ago": 0.35,
  in: 0.12,
};
