export const OPERATION_TYPES = {
  PRODUCT_SYNC: "PRODUCT_SYNC",
  BULK_EDIT: "BULK_EDIT",
  EXPORT: "EXPORT",
  SCHEDULED_EDIT: "SCHEDULED_EDIT",
  AUTOMATIC_RULE: "AUTOMATIC_RULE",
  UNDO: "UNDO",
  IMPORT: "IMPORT",
};
