export const UNDO_CONFLICT_REASONS = Object.freeze({
  PRODUCT_MISSING: "PRODUCT_MISSING",
  VARIANT_MISSING: "VARIANT_MISSING",
  MERCHANT_OR_APP_CHANGED_VALUE_AFTER_EDIT:
    "MERCHANT_OR_APP_CHANGED_VALUE_AFTER_EDIT",
  CURRENT_VALUE_DIFFERS_FROM_AFTER_VALUE: "CURRENT_VALUE_DIFFERS_FROM_AFTER_VALUE",
  FIELD_NOT_SUPPORTED_FOR_UNDO: "FIELD_NOT_SUPPORTED_FOR_UNDO",
  SHOPIFY_SYNC_STALE: "SHOPIFY_SYNC_STALE",
  ANOTHER_OPERATION_TOUCHED_FIELD: "ANOTHER_OPERATION_TOUCHED_FIELD",
});
